"""
Functional Enrichment Visualization & Network Connectivity Pipeline
Author: Charlotte Williamson

Description:
Translates downstream functional enrichment outputs (e.g., from gProfiler) into 
publication-ready figures for Neuronal and Oligodendrocyte lineages. Generates advanced 
bubble plots to illustrate pathway significance versus gene rich factors across Gene 
Ontology (GO) scopes. Constructs custom dual-ring bipartite networks using NetworkX 
to map explicit, edge-curved connections between high-confidence pathway terms (inner ring) 
and their overlapping annotated driver genes (outer ring).

Inputs:
  - data/gProfiler_hsapiens_intersections_neuron.csv
  - data/gProfiler_hsapiens_intersections_oligo.csv

Outputs:
  - results/Enrichment_Bubble_Neurons.png
  - results/Enrichment_Bubble_Oligodendrocytes.png
  - results/Gene_Pathway_Network_Neurons.png
  - results/Gene_Pathway_Network_Oligodendrocytes.png
"""

import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import seaborn as sns
import textwrap
import os
from matplotlib.ticker import ScalarFormatter

#Paths
data_dir = "data"
output_dir = "results"

if not os.path.exists(output_dir):
    os.makedirs(output_dir, exist_ok=True)

#Input CSVs for functional enrichment results (assumed to be pre-generated by gProfiler or similar tool)
NEURON_CSV = os.path.join(data_dir, "gProfiler_hsapiens_intersections_neuron.csv")
OLIGO_CSV  = os.path.join(data_dir, "gProfiler_hsapiens_intersections_oligo.csv")

#Generic Output Image Framework
BUBBLE_NEURON_OUT = os.path.join(output_dir, "Enrichment_Bubble_Neurons.png")
BUBBLE_OLIGO_OUT  = os.path.join(output_dir, "Enrichment_Bubble_Oligodendrocytes.png")
RING_NEURON_OUT   = os.path.join(output_dir, "Gene_Pathway_Network_Neurons.png")
RING_OLIGO_OUT    = os.path.join(output_dir, "Gene_Pathway_Network_Oligodendrocytes.png")

#Colour scheme
COLOUR_PATHWAY = "#2D8B8B"  # Teal
COLOUR_GENE    = "#D1B3E0"  # Purple

#Plotting functions

def generate_enrichment_bubble_plot(file_path, save_path, cell_type_label, ontology_scope):
    #Generates a bubble plot for functional enrichment results, emphasising the top 20 significant terms with a rich visual encoding of significance and gene counts.
    print(f"--- Generating Bubble Plot for {cell_type_label} ({ontology_scope}) ---")
    df = pd.read_csv(file_path)
    
    #Isolate the top 20 most significant terms based on adjusted p-value
    df = df.sort_values('adjusted_p_value').head(20)
    df = df.iloc[::-1].reset_index(drop=True)

    #Calculate structural Rich Factor metrics
    df['rich_factor'] = df['intersection_size'] / df['term_size']
    df['term_name_wrapped'] = df['term_name'].apply(lambda x: textwrap.fill(x, width=45))

    plt.figure(figsize=(14, 12))
    sns.set_style("whitegrid")

    #Main data array layer
    scatter = plt.scatter(
        x=df['rich_factor'], 
        y=df['term_name_wrapped'], 
        s=df['intersection_size'] * 20, 
        c=df['adjusted_p_value'], 
        cmap='viridis', 
        alpha=0.8, 
        edgecolors="black", 
        linewidth=1.2,
        zorder=3
    )

    plt.xscale('log')

    #Colorbar management with inverted axis to prioritise strong significance values
    cbar = plt.colorbar(scatter, fraction=0.046, pad=0.04)
    cbar.set_label('Adjusted p-value (Benjamini-Hochberg FDR)', fontsize=12, fontweight='bold')
    cbar.ax.invert_yaxis()

    #Annotate absolute values explicitly inside the bubble centers
    for i, row in df.iterrows():
        plt.annotate(
            str(int(row['intersection_size'])), 
            xy=(row['rich_factor'], row['term_name_wrapped']),
            ha='center', 
            va='center',
            fontsize=9, 
            fontweight='bold',
            color='black', 
            zorder=4
        )

    #Establish static reference legend indicators
    handles, labels = [], []
    legend_sizes = [4, 30, 55, 80] 
    for size in legend_sizes:
        handles.append(plt.scatter([], [], s=size * 20, c='lightgray', alpha=0.5, edgecolors='black'))
        labels.append(f'{size} genes')

    plt.legend(
        handles, labels, title="Number of Genes", loc="upper right", 
        frameon=True, borderpad=2.0, labelspacing=4.0, handletextpad=1.5
    )

    plt.title(f'Pathway Enrichment Analysis ({cell_type_label})\nScope: {ontology_scope}', fontsize=16, fontweight='bold', pad=25)
    plt.xlabel('Rich Factor (Log Scale)', fontsize=14, labelpad=10)
    plt.ylabel('Enriched Pathway Term', fontsize=14)

    plt.gca().xaxis.set_major_formatter(ScalarFormatter())
    plt.xticks([0.01, 0.02, 0.04, 0.06, 0.1, 0.2, 0.4])

    plt.tight_layout()
    plt.savefig(save_path, dpi=600, bbox_inches='tight')
    plt.close()
    print(f"SUCCESS: Plot exported safely to: {save_path}")


def generate_concentric_ring_network(file_path, save_path, cell_type_label):
    #Generates a concentric ring network visualisation to illustrate the relationships between enriched pathways and their associated genes, with a focus on clarity and interpretability for the top 5 significant terms.
    print(f"--- Generating Interactive Ring Network for {cell_type_label} ---")
    df = pd.read_csv(file_path).head(5)  #Enforce the top 5 enriched terms specified in legend
    G = nx.Graph()

    for i, row in df.iterrows():
        pathway = textwrap.fill(row['term_name'], width=15)
        genes = row['intersections'].split(',')[:8]  # Capture up to 8 coding gene nodes to optimize text density
        G.add_node(pathway, node_type='pathway')
        for gene in genes:
            G.add_node(gene, node_type='gene')
            G.add_edge(pathway, gene)

    pathway_nodes = [n for n, v in G.nodes(data=True) if v['node_type'] == 'pathway']
    gene_nodes    = [n for n, v in G.nodes(data=True) if v['node_type'] == 'gene']

    def get_ring_pos(nodes, radius):
        n = len(nodes)
        return {
            node: np.array([radius * np.cos(2 * np.pi * j / n), 
                            radius * np.sin(2 * np.pi * j / n)])
            for j, node in enumerate(nodes)
        }

    #Pin layout coordinates to distinct inner and outer ring radiuses
    pos_inner = get_ring_pos(pathway_nodes, radius=1.0)
    pos_outer = get_ring_pos(gene_nodes, radius=2.5)
    pos = {**pos_inner, **pos_outer}

    plt.figure(figsize=(15, 15))
    ax = plt.gca()

    pathway_size = 6000 
    gene_size    = 1600
    node_sizes_list = [pathway_size if G.nodes[n]['node_type'] == 'pathway' else gene_size for n in G.nodes()]

    #Draw curved edges to keep the inner ring architecture readable
    nx.draw_networkx_edges(
        G, pos, 
        width=1.2, 
        edge_color='#DCDCDC', 
        alpha=0.6,
        node_size=node_sizes_list,
        connectionstyle="arc3,rad=0.1" 
    )

    #Core node and text placement
    nx.draw_networkx_nodes(G, pos, nodelist=pathway_nodes, node_color=COLOUR_PATHWAY, node_size=pathway_size)
    nx.draw_networkx_nodes(G, pos, nodelist=gene_nodes, node_color=COLOUR_GENE, node_size=gene_size, edgecolors='white')
    nx.draw_networkx_labels(G, pos, font_size=10, font_weight='bold')

    ax.margins(0.3) 
    plt.axis('off')
    plt.title(f"Marker Gene-Pathway Connectivity Network ({cell_type_label})", fontsize=18, fontweight='bold', pad=40)
    
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.savefig(save_path, dpi=600)
    plt.close()
    print(f"Network exported to: {save_path}")

#Pipeline execution

if __name__ == "__main__":
    
    #Neuronal Enrichment Processing
    if os.path.exists(NEURON_CSV):
        generate_enrichment_bubble_plot(NEURON_CSV, BUBBLE_NEURON_OUT, "Neurons", "GO:BP")
        generate_concentric_ring_network(NEURON_CSV, RING_NEURON_OUT, "Neurons")
    else:
        print(f"Skipping Neuron workflows: Missing source reference file '{NEURON_CSV}'")

    #Oligodendrocyte Enrichment Processing
    if os.path.exists(OLIGO_CSV):
        generate_enrichment_bubble_plot(OLIGO_CSV, BUBBLE_OLIGO_OUT, "Oligodendrocytes", "GO:BP, GO:MF, GO:CC")
        generate_concentric_ring_network(OLIGO_CSV, RING_OLIGO_OUT, "Oligodendrocytes")
    else:
        print(f"Skipping Oligodendrocyte workflows: Missing source reference file '{OLIGO_CSV}'")
        
    print("\nDone")